name: advanced event activity type action workflow
on:
  push:
  issues:
    types:
      - opened
      - edited
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          echo github.event_name: "${{ github.event_name }}"
          echo Run Test
