name: First workflow2
on: push
jobs:
  first-job2:
    runs-on: ubuntu-latest
    steps:
      - name: github checkout
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
