name: Matrix workflow
on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [18, 30, 20]
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: install dependencies
        run: npm install axios
      - name: Run Test
        run: echo Run Test
